# Generated by Django 4.2.4 on 2023-09-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_userprofiles_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='username',
        ),
    ]
